name: Setup Python Environment
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: centos:7

    steps:
      - name: Install development tools and dependencies
        run: |
          yum update -y
          yum groupinstall -y "Development Tools"
          yum install -y openssl-devel bzip2-devel libffi-devel xz-devel wget

      - name: Install Python 3.10 from source
        run: |
          cd /tmp
          wget https://www.python.org/ftp/python/3.10.13/Python-3.10.13.tgz
          tar xzf Python-3.10.13.tgz
          cd Python-3.10.13
          ./configure --enable-optimizations --with-ensurepip=install
          make -j $(nproc)
          make altinstall
          ln -sf /usr/local/bin/python3.10 /usr/local/bin/python3
          ln -sf /usr/local/bin/pip3.10 /usr/local/bin/pip3

      - name: Verify Python installation
        run: |
          python3 --version
          pip3 --version

      - name: Create and activate virtual environment
        run: |
          python3 -m venv /opt/venv
          . /opt/venv/bin/activate
          pip3 install --upgrade pip setuptools wheel

      - name: Install required packages
        run: |
          . /opt/venv/bin/activate
          pip3 install langchain "chromadb<0.4.0" ollama

      - name: Verify installations
        run: |
          . /opt/venv/bin/activate
          python3 -c "import langchain; import chromadb; print('Packages successfully installed!')"

      - name: Create portable archive
        run: |
          tar -czf python-env.tar.gz /opt/venv /usr/local/bin/python* /usr/local/lib/python3.10 /usr/local/include/python3.10

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-environment
          path: python-env.tar.gz
