name: Build Portable Python Environment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t portable-python-env .

      - name: Create container from image
        run: |
          docker create --name portable-python-container portable-python-env

      - name: Copy tarball from container
        run: |
          docker cp portable-python-container:/app/python-venv.tar.gz .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: portable-python-venv
          path: python-venv.tar.gz
