name: Build Portable Python Environment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t portable-python-env .

    - name: Create Container and Extract Artifact
      run: |
        container_id=$(docker create portable-python-env)
        docker cp $container_id:/python_env.tar.gz ./python_env.tar.gz
        docker rm $container_id

    - name: Upload artifact
      uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: python_env.tar.gz
        path: ./python_env.tar.gz
