name: Create Python Virtual Environment

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  create-venv:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.9.10"
    
    - name: Create and populate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install ollama langchain chromadb
        deactivate
    
    - name: Create site-packages archive
      run: |
        cd venv/lib/python3.9/site-packages
        tar czf ../../../../site-packages.tar.gz ./*
    
    - name: Upload virtual environment artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-site-packages
        path: site-packages.tar.gz
        if-no-files-found: error

    - name: List installed packages
      run: |
        source venv/bin/activate
        pip freeze > requirements.txt
        deactivate
        cat requirements.txt

    - name: Upload requirements.txt
      uses: actions/upload-artifact@v3
      with:
        name: requirements
        path: requirements.txt
        if-no-files-found: error
