name: Build Portable Python Environment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: python-portable-builder:latest
        
    - name: Extract portable Python archive
      run: |
        docker create --name temp python-portable-builder:latest
        docker cp temp:/python-portable.tar.gz .
        docker rm temp
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: portable-python-3.10
        path: python-portable.tar.gz
        retention-days: 30
